# -*- coding: utf-8 -*-
"""Assignment_03.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VHWrdpejCYviWlVm3KMy09HgkHWDgy-t

#1. Why are functions advantageous to have in your programs?

Ans: **Functions** always can be code reusebility, less code, define one method to solve unlimited trials ,readable , reduces the duplicate of code, easier to update and delete.

# 2.When does the code in a function run: When its speciefied or when its called

Ans: The code of the function will be executed or run, When function will be called that moment of action.
"""

def test():
  pass

"""#3.What statement creates a function?
Ans: The **def** statement will define the definition of function.
"""

def test9(a,b):
  return a + b

test9(3,6)

"""#4.What is the difference between a function and a function call?

Ans: 
**Function**
```
Function is mainly an bulk of code which will executes when it will be called, you can pass the data.
Function will be defined by the keyword called **def**

```
**function call**
```
function call mainly passes control and arguments to a function definition.
mainly controls the function
```
"""

def test():
  print("Hello!!")

test()

"""#5. How many global scopes are there in a Python program? How many local scopes?
Ans: There is only one global scope are there in a python program.this scope will be there untill program terminates.
```
There is mainly four local scopes - LEGB rule
1.Local
2.Enclosing
3.Global
4.built-in

local scope is mainly created whenever function will be called.
```

#6. What happens to variables in a local scope when the function call returns?
Ans: When the function call returns, the local scope will be **destroyed** since local variable is recognised inside the function.

#7. What is the concept of a return value? Is it possible to have a return value in an expression?
Ans: The concept of return value is mainly located inside the functions or method. and performs the functions result. The return value having keyword called **return**. return is mainly gives primitive data type as an output.
```
return value can be used as an expression. where it mainly execution of the function call and returns to result.
```
"""

def test(a,b):
  return a + b
test(1,2)

type(test(1,2))

"""#8. If a function does not have a return statement, what is the return value of a call to that function?
Ans: If there is no return statement to perform means its return value of a call to that function is **None**
"""

def test():
  print(45)

test()

type(test())

"""#9. How do you make a function variable refer to the global variable?
Ans: Always variable created inside the function, that variable commonly as local variable and only using inside the function. But once to create global variable inside a function means you need to create **global** keyword

#10. What is the data type of None?
Ans:data type of None is NoneType

#11. What does the sentence import areallyourpetsnamederic do?
Ans: It is not an real python module. or an library

#12. If you had a bacon() feature in a spam module, what would you call it after importing spam?
Ans: this is function **spam.bacon()**

#13. What can you do to save a programme from crashing if it encounters an error?
Ans: skipping the code inbetween, Try and running the program and place the line of code which will cause an error in a try clause.

#14. What is the purpose of the try clause? What is the purpose of the except clause?
Ans:
```
1.try clause is mainly allow to test a block of code for errors.
2.except clause is mainly handle the type of errors which are facing in an program.
```
"""